### ISSUE TITLE
Query Server Get Down After 1Hr or less

### ISSUE THREAD

**Issue by naeempasha82** [rnewson/couchdb-lucene#242]
i use the command to run/up the query server like as
root@DB1:~/couchdb-lucene-1.1.0/target/couchdb-lucene-1.1.0# ./bin/run
and get response after that as
INFO [Config] Index output goes to: /root/couchdb-lucene-1.1.0/target/couchdb-lucene-1.1.0/indexes
INFO [Main] Accepting connections with SelectChannelConnector@localhost:5985
INFO [insightout] Indexing from update_seq start
INFO [insightout] View[name=_design/lucene/device_reading, digest=689to58gzlmehprwq283ogo8e] now at update_seq 39988

and i checked on other terminal window to using the command as:
curl 127.0.0.1:5985 and get response 
{"couchdb-lucene":"Welcome","version":"1.1.0"}
the things are good and going fine till here but when i close the terminal or remain open then query server get shutdown or stopped after 1hr or less and then i check 
curl 127.0.0.1:5985 get response 
curl: (7) couldn't connect to host

Kindly help me out on this issue Thanks in advance

**Comment by rnewson** [comment]
bin/run runs in the foreground, so closing the terminal will end that process.

I suggest you use runit or systemd or supervisord to ensure couchdb-lucene is always running and automatically restarted should it crash.

If you have some logs or console output related to a crash or unexpected process end, that would help me to help you further.

**Comment by naeempasha82** [comment]
[Tue, 07 Feb 2017 21:27:40 GMT] [error] [<0.271.0>] httpd 500 error response:
 {"error":"error","reason":"{conn_failed,{error,econnrefused}}"}

can you explain me how can i use these commands  "runit or systemd or supervisord" to run the couchdb-lucene. i did try a lot but not success thnx

**Comment by rnewson** [comment]
There are many tutorials on using the process supervising tools I've mentioned, and there are others. I suggest you use whichever tools you are most familiar with for daemonizing important services. I recommend runit (http://smarden.org/runit/) for its simplicity.

The error you show is from couchdb and just tells us that it can't contact couchdb-lucene, it unfortunately doesn't provide any more information than that. Look in the couchdb-lucene.log for more details. However, if this is all solely because you closed the terminal you were running couchdb-lucene in then there's no mystery. Closing the terminal will kill the process running inside it. If couchdb-lucene is terminating in any other circumstance then please send the output of any error from the terminal in which it was running.

**Comment by naeempasha82** [comment]
i have installed the runit successfully but what to do next to run the couchdb-lucene. can you give me any idea?? 
thnx

**Comment by rnewson** [comment]
Their site has lots of examples at http://smarden.org/runit/runscripts.html

Sorry I cannot help further.

**Comment by naeempasha82** [comment]
i did many tries but i am unable to start couchdb-lucene plz help me out on this......

thanks

**Comment by naeempasha82** [comment]
opppps, you just let me know the specific script. now i am trying "sudo couchdb-lucene start" or "./bin/run" so what should i do new after installing the runit to start the lucene server ???

**Comment by rnewson** [comment]
Sorry, I am travelling. Your problem is not with couchdb-lucene.

**Comment by naeempasha82** [comment]
issue has been resolved. now the lucene-server is running into background successfully thanks for your help and your time.

Thank You!

**Comment by rnewson** [comment]
Great!
